on:
    push:
        branches:
            - master

    pull_request:
        types: [opened, edited]
        branches:
            - master

    workflow_dispatch:

jobs:
    test-on-ubuntu:
        name: Testing Workflow Linux

        runs-on: ubuntu-latest

        env:
            SIGNER_CERT: ${{ secrets.SIGNER_CERT }}
            SIGNER_KEY: ${{ secrets.SIGNER_KEY }}
            WWDR: ${{ secrets.WWDR }}
            SIGNER_KEY_PASSPHRASE: ${{ secrets.SIGNER_KEY_PASSPHRASE }}

        steps:
            - uses: pnpm/action-setup@v6
              with:
                  version: 11

            - uses: actions/checkout@v7

            - uses: actions/setup-node@v7
              with:
                  node-version: 24
                  check-latest: true

            - run: |
                  pnpm install
                  pnpm build
                  pnpm test
